### ISSUE TITLE
Asking some questions

### ISSUE THREAD

**Issue by Astromis** [urkax/rule-based-music-generation#1]
Hello.

I'm very excited to find your work. Unfortunately, I have some issues with Chinese language so I would like to hearty ask you to translate the comments and readme into English please.

One more thing. Could you please give a reference to a method you used in this project?

**Comment by zaocan666** [comment]
@Astromis
The reference is [https://github.com/epranka/soundcode](url)
You can look at this repo, and let me know if you still need the translation for readme.

**Comment by Astromis** [comment]
@urkax 
Thank you
